### ISSUE TITLE
15. PERFIL2

### ISSUE THREAD

**Issue by claudiamoyano** [eric-escrich/app-biblIETI#3]
Els usuaris només poden editar la foto de perfil, la resta de dades personals estaran bloquejades.

**Comment by eric-escrich** [comment]
Falta hacer hacer el html y css
Se obtiene la imagen del usuario y si se pulsa encima se puede camiar.

**Comment by eric-escrich** [comment]
Se accede desde el dashboard, pulsando sobre los datos de perfil
